name: default
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Start PG container
      run: docker run -d -p 9091:9091 prom/pushgateway
    - name: Run tests
      run: lein test
    - name: Stop all containers
      if: always()
      run: docker stop $(docker ps -a -q)
    - name: Remove all containers
      if: always()
      run: docker rm $(docker ps -a -q)