name: default
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      pushgateway:
        image: prom/pushgateway
        ports:
        - 9091:9091/tcp
      pushgateway-with-path-prefix:
        image: prom/pushgateway
        ports:
          - 19091:9091/tcp
        command: --web.external-url "/path/prefix"
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@4c7a6f613e5089821bb3bb2a33a3ee115578580d # 13.6.1
      with:
        cli: 1.10.1.693
    - name: Run tests
      run: clojure -X:test
