name: default
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      pushgateway:
        image: prom/pushgateway
        ports:
        - 9091:9091/tcp
    steps:
    - uses: actions/checkout@v4
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@13.1
      with:
        cli: 1.10.1.693
    - name: Run tests
      run: clojure -X:test
