name: default
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      pushgateway:
        image: prom/pushgateway
        ports:
        - 9091:9091/tcp
      pushgateway-with-path-prefix:
        image: prom/pushgateway
        ports:
          - 19091:9091/tcp
        command: --web.external-url "/path/prefix"
    steps:
    - uses: actions/checkout@v6
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@13.5
      with:
        cli: 1.10.1.693
    - name: Run tests
      run: clojure -X:test
